import type { Metadata } from "next";
import * as Com from "@/components/index";
import "./globals.css";

export const metadata: Metadata = {
  title: "CyberSoft Vantage",
  description: "Generated by create next app",
  icons: {
    icon: ["/favion.ico?v=4"],
    apple: ["/favicon-16x16.png"],
    shortcut: ["/apple-touch-icon.png "],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`scroll-smooth text-xl `}>
        <Com.Header />
        {children}
        <Com.SuccessSnippets />
        <Com.Form />
        <Com.Footer />
      </body>
    </html>
  );
}
